In [0]:
import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
from numpy import float32, int32

UBIT = 'rohanhem'
np.random.seed(sum([ord(c) for c in UBIT]))


MIN_MATCH_COUNT = 11

img1 = cv.imread('mountain1.jpg',0)          # queryImage
img2 = cv.imread('mountain2.jpg',0) # trainImage

#initiate sift detector
sift = cv.xfeatures2d.SIFT_create()

# find the keypoints and descriptors with SIFT
kp1, des1 = sift.detectAndCompute(img1,None)
kp2, des2 = sift.detectAndCompute(img2,None)

FLANN_INDEX_KDTREE = 1

index_params = dict(algorithm = FLANN_INDEX_KDTREE, trees = 5)
search_params = dict(checks = 50)

flann = cv.FlannBasedMatcher(index_params, search_params)
matches = flann.knnMatch(des1,des2,k=2)

# store all the good matches as per Lowe's ratio test.
good = []
matchesMask = []
for m,n in matches:
    if m.distance < 0.75*n.distance:
        good.append(m)

matchesMask = np.int32(matchesMask)
if len(good)>MIN_MATCH_COUNT:
    src_pts = np.float32([ kp1[m.queryIdx].pt for m in good ]).reshape(-1,1,2)
    dst_pts = np.float32([ kp2[m.trainIdx].pt for m in good ]).reshape(-1,1,2)
    
    M, mask = cv.findHomography(src_pts, dst_pts, cv.FM_RANSAC,5.0)    
    
   # matchesMask = matchesMask[mask.ravel()==1]
    
    matchesMask = mask.ravel().tolist()
    
    h,w = img1.shape
    
    pts = np.float32([[0,0],[0,h-1],[w-1,h-1],[w-1,0] ]).reshape(-1,1,2)
    dst = cv.perspectiveTransform(pts,M)
    
   # img2 = cv.polylines(img2,[np.int32(dst)],True,255,3, cv.LINE_AA)

else:
    print( "Not enough matches are found - {}/{}".format(len(good), MIN_MATCH_COUNT) )
    matchesMask = None
np.random.shuffle(matchesMask)
matchesMask = matchesMask[:10]
# np.random.shuffle(good)
# good = good[:10]
draw_params = dict(matchColor = (0,255,0), # draw matches in green color
                   singlePointColor = None,
                   matchesMask = matchesMask, # draw only inliers
                   flags = 2)

img3 = cv.drawMatches(img1,kp1,img2,kp2,good,None,**draw_params)

cv.imwrite('task1_matches.jpg', img3)

print (M)

[[ 1.55957349e+00 -2.92880592e-01 -3.86273763e+02]
 [ 4.37559262e-01  1.40210289e+00 -1.84063349e+02]
 [ 1.17252237e-03 -8.91956295e-05  1.00000000e+00]]
